### ISSUE TITLE
Crash on 1.11.2 4.3.3 version with rftools teleporter

### ISSUE THREAD

**Issue by HammerDave** [blay09/NetherPortalFix#13]
Using a rftools matter transmitter/receiver to go to nether because we're experiencing annoying (though not very impactful) damage on arrival using regular nether portals.  Note it's possible to change the destination with a rftools dialer, so you can go from point A in OW to point B in nether and intentionally to point C in OW (or another dimension).

It's crashing with a null pointer.  Not a solid crash, it seems to go through a cycle of hitting a couple times and then it's fine for a while.

Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at net.minecraft.util.math.Vec3i.func_177951_i(SourceFile:211)
	at net.blay09.mods.netherportalfix.NetherPortalFix.storeReturnPortal(NetherPortalFix.java:162)
	at net.blay09.mods.netherportalfix.NetherPortalFix.onPlayerChangedDimension(NetherPortalFix.java:82)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_828_NetherPortalFix_onPlayerChangedDimension_PlayerChangedDimensionEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerChangedDimensionEvent(FMLCommonHandler.java:569)
	at net.minecraft.server.management.PlayerList.transferPlayerToDimension(PlayerList.java:606)
	at mcjty.rftools.blocks.teleporter.TeleportationTools.teleportToDimension(TeleportationTools.java:362)
	at mcjty.rftools.blocks.teleporter.TeleportationTools.performTeleport(TeleportationTools.java:151)
	at mcjty.rftools.blocks.teleporter.MatterTransmitterTileEntity.performTeleport(MatterTransmitterTileEntity.java:524)
	at mcjty.rftools.blocks.teleporter.MatterTransmitterTileEntity.checkStateServer(MatterTransmitterTileEntity.java:363)
	at mcjty.rftools.blocks.teleporter.MatterTransmitterTileEntity.func_73660_a(MatterTransmitterTileEntity.java:306)
	at net.minecraft.world.World.func_72939_s(World.java:1802)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)

**Comment by BlayTheNinth** [comment]
This, along with the damage on teleport should be fixed in the latest version now.
