### ISSUE TITLE
Bad lag when going through nether portal

### ISSUE THREAD

**Issue by hampsterblade** [blay09/NetherPortalFix#23]
Major lag when first going into the nether.  Server errored multiple times and locked up.
```
[22:33:30] [Server thread/INFO] [FML]: Loading dimension -1 (world) (net.minecraft.server.dedicated.DedicatedServer@40d3c715)
[22:33:31] [Server thread/INFO] [NetherEx|PigtificateVillageManager]: The Pigtificate Village data for nether was read successfully.
[22:33:31] [Server thread/INFO] [THAUMCRAFT]: Creating aura cache for world -1
[22:33:45] [Server thread/INFO] [journeymap]: pixiepunk500 joining dimension -1
[22:33:45] [Server thread/ERROR] [FML]: FMLIndexedMessageCodec exception caught
io.netty.handler.codec.EncoderException: java.lang.RuntimeException: Undefined discriminator for message type DimensionPermissionPacket in channel jm_dim_permission
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:106) ~[MessageToMessageEncoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[AbstractChannelHandlerContext.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[AbstractChannelHandlerContext.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[AbstractChannelHandlerContext.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[AbstractChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[AbstractChannel.class:?]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendTo(SimpleNetworkWrapper.java:250) [SimpleNetworkWrapper.class:?]
	at journeymap.common.network.PacketHandler.sendDimensionPacketToPlayer(PacketHandler.java:60) [PacketHandler.class:1.12.2-5.5.2]
	at journeymap.server.events.ForgeEvents.on(ForgeEvents.java:68) [ForgeEvents.class:1.12.2-5.5.2]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_773_ForgeEvents_on_EntityJoinWorldEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraft.world.World.func_72838_d(World.java:1205) [amu.class:?]
	at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:1058) [oo.class:?]
	at net.minecraft.server.management.PlayerList.transferEntityToWorld(PlayerList.java:721) [pl.class:?]
	at net.minecraft.server.management.PlayerList.transferPlayerToDimension(PlayerList.java:623) [pl.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.changeDimension(EntityPlayerMP.java:695) [oq.class:?]
	at net.minecraft.entity.Entity.func_184204_a(Entity.java:2540) [vg.class:?]
	at net.minecraft.entity.Entity.func_70030_z(Entity.java:441) [vg.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:224) [vp.class:?]
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:388) [vg.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2087) [vp.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234) [aed.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) [oq.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) [pa.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) [NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) [gw.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_172]
Caused by: java.lang.RuntimeException: Undefined discriminator for message type DimensionPermissionPacket in channel jm_dim_permission
	at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:72) ~[FMLIndexedMessageToMessageCodec.class:?]
	at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67) ~[MessageToMessageCodec$1.class:?]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88) ~[MessageToMessageEncoder.class:?]
	... 35 more
[22:33:45] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: pixiepunk500Ȳ has made the advancement Ȳȡ[ȲȡWe Need to Go DeeperȲȡ]Ȳ
[22:33:45] [Server thread/WARN] [net.minecraft.server.MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 14276ms behind, skipping 285 tick(s)
[22:33:45] [Thread-485/INFO] [THAUMCRAFT]: Starting aura thread for dim -1
[22:33:48] [Server thread/WARN] [net.minecraft.network.NetHandlerPlayServer]: pixiepunk500 moved too quickly! 357.27668322618626,-11.0,-248.71154284102533
[22:34:03] [Server thread/WARN] [net.minecraft.server.MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 5525ms behind, skipping 110 tick(s)
[22:34:04] [Server thread/INFO] [journeymap]: pixiepunk500 joining dimension 0
[22:34:04] [Server thread/ERROR] [FML]: FMLIndexedMessageCodec exception caught
io.netty.handler.codec.EncoderException: java.lang.RuntimeException: Undefined discriminator for message type DimensionPermissionPacket in channel jm_dim_permission
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:106) ~[MessageToMessageEncoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[AbstractChannelHandlerContext.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[AbstractChannelHandlerContext.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[AbstractChannelHandlerContext.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[AbstractChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[AbstractChannel.class:?]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendTo(SimpleNetworkWrapper.java:250) [SimpleNetworkWrapper.class:?]
	at journeymap.common.network.PacketHandler.sendDimensionPacketToPlayer(PacketHandler.java:60) [PacketHandler.class:1.12.2-5.5.2]
	at journeymap.server.events.ForgeEvents.on(ForgeEvents.java:68) [ForgeEvents.class:1.12.2-5.5.2]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_773_ForgeEvents_on_EntityJoinWorldEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraft.world.World.func_72838_d(World.java:1205) [amu.class:?]
	at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:1058) [oo.class:?]
	at net.blay09.mods.netherportalfix.NetherPortalFix.transferEntityToWorld(NetherPortalFix.java:147) [NetherPortalFix.class:?]
	at net.blay09.mods.netherportalfix.NetherPortalFix.transferPlayerToDimension(NetherPortalFix.java:172) [NetherPortalFix.class:?]
	at net.blay09.mods.netherportalfix.NetherPortalFix.onPlayerTick(NetherPortalFix.java:118) [NetherPortalFix.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_776_NetherPortalFix_onPlayerTick_PlayerTickEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPostTick(FMLCommonHandler.java:369) [FMLCommonHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_184808_cD(EntityPlayer.java:378) [aed.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288) [aed.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) [oq.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) [pa.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) [NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) [gw.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_172]
Caused by: java.lang.RuntimeException: Undefined discriminator for message type DimensionPermissionPacket in channel jm_dim_permission
	at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:72) ~[FMLIndexedMessageToMessageCodec.class:?]
	at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67) ~[MessageToMessageCodec$1.class:?]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88) ~[MessageToMessageEncoder.class:?]
	... 35 more
[22:34:06] [Server thread/INFO] [THAUMCRAFT]: Removing aura cache for world -1
[22:34:07] [Server thread/INFO] [FML]: Unloading dimension -1
[22:34:07] [Thread-485/INFO] [THAUMCRAFT]: Stopping aura thread for dim -1
[22:34:07] [Server thread/WARN] [net.minecraft.network.NetHandlerPlayServer]: pixiepunk500 moved too quickly! -356.7852443302605,11.0,249.85612415417899
```

**Comment by BlayTheNinth** [comment]
This is an issue in JourneyMap: https://github.com/TeamJM/journeymap/issues/42
